export interface Listing {
  id: string;
  title: string;
  brand: string;
  category: string;
  size: string;
  condition: 'like-new' | 'good' | 'fair' | 'well-loved';
  conditionLabel: string;
  estimatedValue: number;
  swapValueRange: [number, number];
  imageUrl: string;
  imageAlt: string;
  ownerName: string;
  ownerAvatar: string;
  ownerCity: string;
  distanceMiles: number;
  tags: string[];
  gender: string;
  postedDaysAgo: number;
  saved: boolean;
  color?: string;
}

export const LISTINGS: Listing[] = [
  {
    id: 'listing-001',
    title: 'Linen Blazer — Sage Green',
    brand: 'Everlane',
    category: 'Outerwear',
    size: 'M',
    condition: 'like-new',
    conditionLabel: 'Like New',
    estimatedValue: 78,
    swapValueRange: [60, 90],
    imageUrl: 'https://img.rocket.new/generatedImages/rocket_gen_img_1fc60a057-1784221581537.png',
    imageAlt:
      'Sage green linen blazer laid flat on white surface, structured shoulders and button closure',
    ownerName: 'Priya Sharma',
    ownerAvatar: 'PS',
    ownerCity: 'Portland, OR',
    distanceMiles: 1.2,
    tags: ['Minimalist', 'Workwear'],
    gender: 'Women',
    postedDaysAgo: 2,
    saved: false,
    color: '#8FBC8F',
  },
  {
    id: 'listing-002',
    title: "Vintage Levi's 501 Jeans",
    brand: "Levi's",
    category: 'Bottoms',
    size: '28',
    condition: 'good',
    conditionLabel: 'Good',
    estimatedValue: 55,
    swapValueRange: [45, 65],
    imageUrl: 'https://img.rocket.new/generatedImages/rocket_gen_img_170d28392-1772621928114.png',
    imageAlt: 'Classic blue Levi 501 straight-leg jeans folded on wooden surface',
    ownerName: 'Jordan Kim',
    ownerAvatar: 'JK',
    ownerCity: 'Seattle, WA',
    distanceMiles: 3.8,
    tags: ['Vintage', 'Casual'],
    gender: 'Unisex',
    postedDaysAgo: 1,
    saved: true,
    color: '#4A90A4',
  },
  {
    id: 'listing-003',
    title: 'Silk Slip Dress — Ivory',
    brand: 'Reformation',
    category: 'Dresses',
    size: 'S',
    condition: 'like-new',
    conditionLabel: 'Like New',
    estimatedValue: 145,
    swapValueRange: [120, 160],
    imageUrl: 'https://img.rocket.new/generatedImages/rocket_gen_img_11eebe6fe-1772209196588.png',
    imageAlt: 'Ivory silk slip dress on hanger against light wall, bias cut with adjustable straps',
    ownerName: 'Camille Dubois',
    ownerAvatar: 'CD',
    ownerCity: 'Portland, OR',
    distanceMiles: 0.7,
    tags: ['Boho', 'Elegant'],
    gender: 'Women',
    postedDaysAgo: 4,
    saved: false,
    color: '#F5F5DC',
  },
  {
    id: 'listing-004',
    title: 'Oversized Wool Sweater',
    brand: 'COS',
    category: 'Tops',
    size: 'L',
    condition: 'good',
    conditionLabel: 'Good',
    estimatedValue: 62,
    swapValueRange: [50, 75],
    imageUrl: 'https://img.rocket.new/generatedImages/rocket_gen_img_123e1249b-1784798292465.png',
    imageAlt: 'Cream oversized wool crew-neck sweater on mannequin with ribbed cuffs and hem',
    ownerName: 'Alex Torres',
    ownerAvatar: 'AT',
    ownerCity: 'Eugene, OR',
    distanceMiles: 8.4,
    tags: ['Minimalist', 'Cozy'],
    gender: 'Unisex',
    postedDaysAgo: 6,
    saved: false,
    color: '#F5F5DC',
  },
  {
    id: 'listing-005',
    title: 'Leather Ankle Boots — Black',
    brand: 'Dr. Martens',
    category: 'Shoes',
    size: '8',
    condition: 'fair',
    conditionLabel: 'Fair',
    estimatedValue: 85,
    swapValueRange: [65, 100],
    imageUrl: 'https://images.unsplash.com/photo-1646475316811-4311b74b8cd1',
    imageAlt: 'Black leather Dr Martens ankle boots with yellow stitching on concrete surface',
    ownerName: 'Sam Okafor',
    ownerAvatar: 'SO',
    ownerCity: 'Portland, OR',
    distanceMiles: 2.1,
    tags: ['Streetwear', 'Edgy'],
    gender: 'Unisex',
    postedDaysAgo: 3,
    saved: false,
    color: '#2C3E50',
  },
  {
    id: 'listing-006',
    title: 'Cropped Denim Jacket',
    brand: 'Madewell',
    category: 'Outerwear',
    size: 'XS',
    condition: 'good',
    conditionLabel: 'Good',
    estimatedValue: 68,
    swapValueRange: [55, 80],
    imageUrl: 'https://img.rocket.new/generatedImages/rocket_gen_img_17d61ba84-1765462017379.png',
    imageAlt: 'Light wash cropped denim jacket with raw hem on clothing rack in natural light',
    ownerName: 'Nadia Petrov',
    ownerAvatar: 'NP',
    ownerCity: 'Beaverton, OR',
    distanceMiles: 5.9,
    tags: ['Casual', 'Y2K'],
    gender: 'Women',
    postedDaysAgo: 1,
    saved: true,
    color: '#87CEEB',
  },
  {
    id: 'listing-007',
    title: 'Linen Wide-Leg Trousers',
    brand: 'Arket',
    category: 'Bottoms',
    size: '30',
    condition: 'like-new',
    conditionLabel: 'Like New',
    estimatedValue: 92,
    swapValueRange: [75, 110],
    imageUrl: 'https://img.rocket.new/generatedImages/rocket_gen_img_1cbe43b7e-1772210386575.png',
    imageAlt:
      'Ecru linen wide-leg trousers with elastic waist on white hanger against neutral wall',
    ownerName: 'Fatima Al-Hassan',
    ownerAvatar: 'FA',
    ownerCity: 'Portland, OR',
    distanceMiles: 1.8,
    tags: ['Minimalist', 'Boho'],
    gender: 'Women',
    postedDaysAgo: 5,
    saved: false,
    color: '#F5F5DC',
  },
  {
    id: 'listing-008',
    title: 'Graphic Tee — Band Print',
    brand: 'Urban Outfitters',
    category: 'Tops',
    size: 'M',
    condition: 'well-loved',
    conditionLabel: 'Well Loved',
    estimatedValue: 18,
    swapValueRange: [12, 25],
    imageUrl: 'https://img.rocket.new/generatedImages/rocket_gen_img_19eb8ce51-1772349107908.png',
    imageAlt: 'Faded black graphic band tee with distressed print laid on wooden floor',
    ownerName: 'Marcus Webb',
    ownerAvatar: 'MW',
    ownerCity: 'Vancouver, WA',
    distanceMiles: 12.3,
    tags: ['Vintage', 'Streetwear'],
    gender: 'Unisex',
    postedDaysAgo: 7,
    saved: false,
    color: '#2C3E50',
  },
  {
    id: 'listing-009',
    title: 'Cashmere Turtleneck — Camel',
    brand: 'Quince',
    category: 'Tops',
    size: 'S',
    condition: 'good',
    conditionLabel: 'Good',
    estimatedValue: 110,
    swapValueRange: [90, 130],
    imageUrl: 'https://img.rocket.new/generatedImages/rocket_gen_img_16385b588-1772088968467.png',
    imageAlt: 'Camel cashmere turtleneck sweater folded neatly showing fine knit texture',
    ownerName: 'Isla MacGregor',
    ownerAvatar: 'IM',
    ownerCity: 'Portland, OR',
    distanceMiles: 3.3,
    tags: ['Minimalist', 'Preppy'],
    gender: 'Women',
    postedDaysAgo: 2,
    saved: false,
    color: '#C19A6B',
  },
  {
    id: 'listing-010',
    title: 'Pleated Midi Skirt — Terracotta',
    brand: '& Other Stories',
    category: 'Bottoms',
    size: 'M',
    condition: 'like-new',
    conditionLabel: 'Like New',
    estimatedValue: 72,
    swapValueRange: [60, 85],
    imageUrl: 'https://img.rocket.new/generatedImages/rocket_gen_img_1a2202393-1772101260576.png',
    imageAlt:
      'Terracotta pleated midi skirt with elastic waist on model outdoors in golden hour light',
    ownerName: 'Zoe Nakamura',
    ownerAvatar: 'ZN',
    ownerCity: 'Portland, OR',
    distanceMiles: 0.4,
    tags: ['Boho', 'Cottagecore'],
    gender: 'Women',
    postedDaysAgo: 1,
    saved: true,
    color: '#E2725B',
  },
  {
    id: 'listing-011',
    title: 'Puffer Vest — Forest Green',
    brand: 'Patagonia',
    category: 'Outerwear',
    size: 'L',
    condition: 'good',
    conditionLabel: 'Good',
    estimatedValue: 95,
    swapValueRange: [80, 115],
    imageUrl: 'https://img.rocket.new/generatedImages/rocket_gen_img_19da1b9cc-1770067397357.png',
    imageAlt:
      'Forest green Patagonia puffer vest on hanger against white wall with zipper detail visible',
    ownerName: 'Eli Greenwald',
    ownerAvatar: 'EG',
    ownerCity: 'Lake Oswego, OR',
    distanceMiles: 7.6,
    tags: ['Athletic', 'Outdoor'],
    gender: 'Unisex',
    postedDaysAgo: 3,
    saved: false,
    color: '#228B22',
  },
  {
    id: 'listing-012',
    title: 'Wrap Blouse — Floral Print',
    brand: 'Anthropologie',
    category: 'Tops',
    size: 'XS',
    condition: 'fair',
    conditionLabel: 'Fair',
    estimatedValue: 38,
    swapValueRange: [28, 48],
    imageUrl: 'https://img.rocket.new/generatedImages/rocket_gen_img_12334c6c2-1772090378013.png',
    imageAlt: 'Floral printed wrap blouse with long sleeves and V-neckline hanging in bright room',
    ownerName: 'Amara Osei',
    ownerAvatar: 'AO',
    ownerCity: 'Portland, OR',
    distanceMiles: 2.6,
    tags: ['Boho', 'Casual'],
    gender: 'Women',
    postedDaysAgo: 8,
    saved: false,
    color: '#FFB6C1',
  },
];

export const CATEGORIES = [
  'All',
  'Tops',
  'Bottoms',
  'Dresses',
  'Outerwear',
  'Shoes',
  'Accessories',
];
export const SIZES = ['XS', 'S', 'M', 'L', 'XL', 'XXL', '24', '26', '28', '30', '32'];
export const CONDITIONS = ['Like New', 'Good', 'Fair', 'Well Loved'];
export const DISTANCES = ['2 miles', '5 miles', '10 miles', '25 miles', 'Any distance'];
export const SORT_OPTIONS = [
  'Newest first',
  'Value: High to Low',
  'Value: Low to High',
  'Closest first',
];
